### ISSUE TITLE
HTM vs HTML extension

### ISSUE THREAD

**Issue by tjvr** [livewires/web-building#3]
The "getting started" script creates an `index.html` file, but we refer to `index.htm` elsewhere in the course (e.g. sheet 2.1).

I propose that we use `.html` everywhere to be consistent.

**Comment by jamesdoc** [comment]
In the JS course I've gone for `.htm`.

If we set that here, we should set that there too...

I'll update both to `.html`

**Comment by tjvr** [comment]
Nice, thanks. 👍
